#!/usr/bin/expect -f

if {$argc<2} { puts stderr "error"; exit 1 }

set REMOTE_IP [lindex $argv 0]
set REMOTE_PASS [lindex $argv 1]
#set HOSTNAME [lindex $argv 2]
set timeout 600
match_max 20000
send_user ">>>>> runcmd  >>>>>\r\n"

spawn ssh root@${REMOTE_IP}
expect "password: "
send  "$REMOTE_PASS\r"


expect "]*"
send "sh ./files_exp/runcmd.sh \r"


send "exit \r"
expect eof { send_user "<<<<< runcmd  <<<<<\n" }
